=== toddb/jquery.storyq/tests/data/results.dtd
<?xml version="1.0" encoding="UTF-8"?>
<!ELEMENT storyq (story+)>
<!ATTLIST storyq
  xmlns CDATA #IMPLIED
  xmlns:sq CDATA #IMPLIED
>
<!ELEMENT story (title?, scenario+)>
<!ATTLIST story
	namespace CDATA #REQUIRED
	category CDATA #IMPLIED
>
<!ELEMENT title (#PCDATA)>
<!ELEMENT scenario (value?, action?, role, action?, value?, narrative*)>
<!ATTLIST scenario
  dialect (AsA | InOrder) #REQUIRED
>
<!ELEMENT role (#PCDATA)>
<!ELEMENT action (#PCDATA)>
<!ELEMENT value (#PCDATA)>
<!ELEMENT narrative (given, and*, when, and*, then, and*)>
<!ELEMENT given (#PCDATA)>
<!ATTLIST given
  result (pending | passed | failed) #IMPLIED
>
<!ELEMENT when (#PCDATA)>
<!ATTLIST when
  result (pending | passed | failed) #IMPLIED
>
<!ELEMENT then (#PCDATA)>
<!ATTLIST then
  result (pending | passed | failed) #IMPLIED
>
<!ELEMENT and (#PCDATA)>
<!ATTLIST and
  result (pending | passed | failed) #IMPLIED
>

=== toddb/jquery.storyq/tests/data/results-01.xml
<?xml version="1.0" encoding="UTF-8"?>
<!DOCTYPE storyq PUBLIC "-//StoryQ//ENTITIES V1.0//EN" "results.dtd">
<storyq xmlns="http://storyq.8wireunlimited.com/schema/results/0.1">
	<story namespace="StoryQ.Tests" category="*">
		<title>This is a user story with multiple scenarios</title>
		<scenario dialect="AsA">
		    <role>{role1}</role>
		    <action>{action}</action>
		    <value>{business value}</value>
		    <narrative>
		      <given result="pending">{I have some condition}1</given>
	          <when result="passed">{I do something}1</when>
			      <then result="failed">{I see this result}1</then>
			      <and>{and I see this result}1</and>
		    </narrative>
		    <narrative>
		      <given result="pending">{I have some condition}2</given>
	          <and result="pending">{I have another given condition}2</and>
	          <when result="pending">{I do something}2</when>
	          <and result="pending">{I have another when condition}2</and>
		      <then result="pending">{I see this result}2</then>
		      <and>{I have another then condition}2</and>
		      <and>{I have (another) second then condition}2</and>
		    </narrative>
		</scenario>
		<scenario dialect="InOrder">
	      <value>{business value}</value>
		    <role>{role2}</role>
		    <action>{action}</action>
		    <narrative>
		      <given result="passed">{I have some condition}3</given>
	          <and result="passed">{I have another given condition}3</and>
	          <when result="passed">{I do something}3</when>
		      <then result="passed">{I see this result}3</then>
		    </narrative>
		    <narrative>
		      <given result="failed">{I have some condition}4</given>
	          <and result="failed">{I have another given condition}4</and>
	          <when result="failed">{I do something}4</when>
		      <then result="failed">{I see this result}4</then>
		    </narrative>
		</scenario>
	</story>	
</storyq>
